# Generated by Django 5.1 on 2024-08-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pandal',
            old_name='uuid_field',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='pandal',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pandal',
            name='longitude',
        ),
        migrations.AddField(
            model_name='pandal',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pandal',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
