# Generated by Django 5.0 on 2024-10-06 00:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("DEBUG", "Debug"),
                            ("ERROR", "Error"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("module", models.CharField(max_length=100)),
                ("user_id", models.UUIDField(default=None, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
