# Generated by Django 5.0 on 2024-10-04 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pujo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("lat", models.FloatField(null=True)),
                ("lon", models.FloatField(null=True)),
                ("address", models.TextField()),
                ("city", models.TextField()),
                ("zone", models.CharField(max_length=100)),
                ("search_score", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
                (
                    "transport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pujos",
                        to="transport.transport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LastScoreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField()),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pujo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_scores",
                        to="pujo.pujo",
                    ),
                ),
            ],
        ),
    ]
