# Generated by Django 5.0 on 2024-10-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pujo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pujo",
            name="nearest_transport_distance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
