# Generated by Django 5.0 on 2024-10-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pujo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastscoremodel",
            name="value",
            field=models.FloatField(),
        ),
    ]
