# Generated by Django 5.0 on 2024-08-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pujo',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
