# Generated by Django 5.0 on 2024-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pujo", "0002_alter_lastscoremodel_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="lastscoremodel",
            name="name",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
