# Generated by Django 5.0 on 2024-09-18 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0002_alter_pujo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pujo',
            name='id',
        ),
        migrations.AlterField(
            model_name='pujo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
