# Generated by Django 5.0 on 2024-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0003_remove_pujo_id_alter_pujo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pujo',
            name='searchScore',
            field=models.IntegerField(default=0),
        ),
    ]
