# Generated by Django 5.0 on 2024-09-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0004_pujo_searchscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pujo',
            old_name='uuid',
            new_name='id',
        ),
    ]
