# Generated by Django 5.0 on 2024-09-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0005_rename_uuid_pujo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pujo',
            old_name='searchScore',
            new_name='search_score',
        ),
    ]
