# Generated by Django 5.0 on 2024-10-01 12:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0006_rename_searchscore_pujo_search_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='pujo',
            name='last_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
