# Generated by Django 5.0 on 2024-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0007_pujo_last_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pujo',
            name='last_score',
        ),
        migrations.AddField(
            model_name='pujo',
            name='last_scores',
            field=models.ManyToManyField(blank=True, to='pujo.lastscoremodel'),
        ),
    ]
