# Generated by Django 5.0 on 2024-10-01 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0008_lastscoremodel_remove_pujo_last_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pujo',
            name='last_scores',
        ),
        migrations.AddField(
            model_name='lastscoremodel',
            name='pujo',
            field=models.ForeignKey(default='85fc002e-6931-4d6a-9995-a15081f8032d', on_delete=django.db.models.deletion.CASCADE, related_name='last_score', to='pujo.pujo'),
            preserve_default=False,
        ),
    ]
