# Generated by Django 5.0 on 2024-10-01 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0009_remove_pujo_last_scores_lastscoremodel_pujo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastscoremodel',
            name='pujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_scores', to='pujo.pujo'),
        ),
    ]
