# Generated by Django 5.0 on 2024-10-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pujo', '0010_alter_lastscoremodel_pujo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pujo',
            name='search_score',
            field=models.IntegerField(default=100),
        ),
    ]
