# Generated by Django 5.0 on 2024-10-04 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pujo", "0011_alter_pujo_search_score"),
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pujo",
            name="transport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pujos",
                to="transport.transport",
            ),
        ),
    ]
