# Generated by Django 5.0 on 2024-09-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
