# Generated by Django 5.0 on 2024-09-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_blacklistedtoken_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklistedtoken',
            old_name='created_at',
            new_name='blacklisted_at',
        ),
    ]
